config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  root 'home#top'

  # ログイン機能
  get    'parent/login', to: 'sessions#parent_login'
  get    'teacher/login', to: 'sessions#teacher_login'
  post   'parent/login', to: 'sessions#parent_create'
  post   'teacher/login', to: 'sessions#teacher_create'
  delete 'parent/logout', to: 'sessions#parent_destroy'
  delete 'teacher/logout', to: 'sessions#teacher_destroy'

  # # LINEログインAPI用
  # get '/parents/auth/line', to: 'parents#line', as: :parents_auth
  # get '/parents/auth/line/callback', to: 'parents#line_login', as: :parents_auth_callback
  # get '/parents/auth/failure', to: 'parents#auth_failure', as: :parents_auth_failure
  
  # get '/teachers/auth/line', to: 'teachers#line', as: :teachers_auth
  # get '/teachers/auth/line/callback', to: 'teachers#line_login', as: :teachers_auth_callback
  # get '/teacheres/auth/failure', to: 'teachers#auth_failure', as: :teachers_auth_failure

  # LINEボットAPI用
  post '/callback' => 'line_bot#callback'

  # 保護者&保護者に紐付く園児
  resources :parents do
    member do
      get 'edit_manag_info' # 管理者が編集可能な情報
      patch 'update_manag_info' # 管理者が編集可能な情報の更新
    end
    resources :children do
      resources :attendances, only: [:update, :index] do
        member do
          get 'confirm_attendance' # 連絡帳確認ボタン
        end
      end
    end
  end

  # 管理者のみが表示可能な園児一覧
  get    'children', to: 'children#all', as: 'all'
  delete 'children/:id', to: 'children#destroy_from_admin', as: 'destroy_from_admin'
  get    'children/edit_class/:id', to: 'children#edit_class', as: 'edit_class'
  patch  'children/update_class/:id', to: 'children#update_class', as: 'update_class'

  # 管理者&保育者
  resources :teachers do
    member do
      get 'edit_manag_info' # 管理者が編集可能な情報
      patch 'update_manag_info' # 管理者が編集可能な情報の更新
      get 'edit_attendance' # 園児の連絡帳画面取得
      patch 'update_attendance/:child_id', to: 'teachers#update_attendance', as: 'update_attendance' # 園児の連絡帳更新
      get 'all_children' # 担当園児一覧表示
      get 'index_attendance/:child_id', to: 'teachers#index_attendance', as: 'index_attendance' # 連絡帳一覧表示
      get 'confirm_attendance/:child_id/:attendance_id', to: 'teachers#confirm_attendance', as: 'confirm_attendance' # 連絡帳確認ボタン
    end
  end

  resources :notices
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :logged_in_parent, only: [:new, :create, :edit, :update, :show]
  before_action :not_admin_teacher, only: [:all, :destroy_from_admin, :edit_class, :update_class]

  # 園児一覧
  def index
    @children = Child.paginate(page: params[:page], per_page: 10)
    if params[:search].present?
      @children = Child.paginate(page: params[:page]).search(params[:search]) 
    end
  end
  
  # 園児追加モーダル表示
  def new
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.new
    @classrooms = Classroom.all
  end

  # 園児追加モーダルでの園児作成
  def create
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.new(child_params)
    if @child.save
      flash[:success] = '子供を追加しました。'
      redirect_to @parent
    else
      flash.now[:danger] = '登録できませんでした。'
      render 'parents/show'
    end
  end

  # 園児情報編集モーダル
  def edit
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.find(params[:id])
    @classrooms = Classroom.where(id: @child.classroom_id)
  end

  # 園児情報編集モーダル更新
  def update
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.find(params[:id])
    if @child.update_attributes(child_params)
      flash[:success] = "園児情報を更新しました。"
      redirect_to @parent
    else
      render :edit 
    end
  end

  # 園児連絡帳提出画面
  def show
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.find(params[:id])
    if params[:date].blank?
      @day = Date.today
    else
      @day = params[:date].to_date
    end
    unless find_attendance?
      @attendance = @child.attendances.create # @attendanceにデータがなかった場合に新規でデータ作成
    end
  end

  # 管理者のみ表示可能な園児一覧
  def all
    @children = Child.paginate(page: params[:page], per_page: 10).order(:classroom_id)
    if params[:search].present?
      @children = Child.paginate(page: params[:page]).search(params[:search]) 
    end
  end

  # 管理者による園児削除
  def destroy_from_admin
    @child = Child.find(params[:id])
    @child.destroy
    flash[:success] = "#{@child.child_name}のデータを削除しました。"
    redirect_to all_url
  end

  # 管理者による園児クラス編集
  def edit_class
    @child = Child.find(params[:id])
  end

  # 管理者による園児クラス更新
  def update_class
    @child = Child.find(params[:id])
    if @child.update_attributes(class_params)
      flash[:success] = "園児情報を更新しました。"
      redirect_to all_url
    else
      render :edit_class 
    end
  end

  private
    # 園児情報
    def child_params
      params.require(:child).permit(:child_name, :age, :birthday, :gender, :classroom_id)
    end

    # @attendanceにデータがあるかどうか
    def find_attendance?
      @attendance = @child.attendances.find_by(worked_on: @day)
      # @attendance = Attendance.find_by(child_id: @child.id, worked_on: @day.to_s)
    end

    # クラス情報
    def class_params
      params.require(:child).permit(:classroom_id)
    end

end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_edit.erb
<% provide(:class_text, 'edit-child') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">園児情報編集</h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= form_with(model: @child, url: parent_child_path(@parent), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @child %>
          
            <%= f.label :child_name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :child_name, class: "form-control" %>
          
            <%= f.label :age, class: "label-#{yield(:class_text)}" %>
            <%= f.number_field :age, class: "form-control", min: 0, max: 5 %>
          
            <%= f.label :birthday, class: "label-#{yield(:class_text)}" %><br>
            <%= f.date_select :birthday,
                {start_year: 2010,
                end_year: (Time.now.year),
                default: Date.new(2020, 1, 1),
                use_month_numbers: true,
                date_separator: '/'} %><br>
                <!-- #date_fieldでカッコよくできる -->
          
            <%= f.radio_button :gender, :man %>
            <%= f.label :gender, "男", {value: :man, style: "display: inline-block;"} %>
            <%= f.radio_button :gender, :woman %>
            <%= f.label :gender, "女", {value: :woman, style: "display: inline-block;"} %><br>
          
            <%= f.label :class_name, class: "label-#{yield(:class_text)}" %>
            <%= @classrooms[0][:class_name] %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/children/_edit.html.erb
<% provide(:class_text, 'edit-child') %>
<% provide(:button_text, '更新') %>

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css">
</head>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">園児情報編集</h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= form_with(model: @child, url: parent_child_path(@parent), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @child %>
          
            <%= f.label :child_name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :child_name, class: "form-control" %>
          
            <%= f.label :birthday, class: "label-#{yield(:class_text)}" %><br>
            <%= f.text_field :birthday, {class: "form-control dp", id: "birthdayYMD"} %>

            <!-- %= raw sprintf(f.date_select( :birthday,
                start_year: 2010,
                end_year: (Time.now.year),
                default: Date.new(2020, 1, 1),
                use_month_numbers: true,
                date_separator: '%s'),'年','月')+'日' %><br>
                #date_fieldでカッコよくできる -->

            <%= f.label :age, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :age, {class: "form-control", id: "nowAge"} %>
          
            <%= f.label :gender %><br>
            <%= f.radio_button :gender, :man %>
            <%= f.label :gender, "男", {value: :man, style: "display: inline-block;"} %>
            <%= f.radio_button :gender, :woman %>
            <%= f.label :gender, "女", {value: :woman, style: "display: inline-block;"} %><br>
          
            <%= f.label :class_name, class: "label-#{yield(:class_text)}" %>
            <%= f.select :classroom_id, [['ひよこ', 1],['あひる', 2], ['ぺんぎん', 3]], {selected: @child.classroom_id, include_blank: false}, class: "form_control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-light btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $(".dp").datepicker( {
      changeYear: true,  // 年選択をプルダウン化
      changeMonth: true,  // 月選択をプルダウン化
      yearRange: "-5:" // 現在日付の5年前～5年後まで選択可能
    } );
  });
</script>

<script>
  $(function(){
    $('#birthdayYMD').change(function() {
      birthday_ymd = $('#birthdayYMD').val();
      retBirth = birthday_ymd.split("/");
      y = parseInt(retBirth[0], 10);
      m = parseInt(retBirth[1], 10);
      d = parseInt(retBirth[2], 10);

      myNow = new Date();    // 現在
      myBirth = new Date( 1970, 0, d );    // 基準日
      myBirth.setTime( myNow.getTime() - myBirth.getTime() );    // getTimeは1970年からの経過ミリ秒数を取得するメソッド

      // 求めた年月日から基準日を引く
      myYear  = myBirth.getUTCFullYear() - y;
      myMonth = myBirth.getUTCMonth() - ( m - 1 );

      // 月がマイナスなので年から繰り下げ
      if( myMonth < 0 ){
          myYear --;
          myMonth += 12;
      }

      // myDate = myBirth.getUTCDate();

      $('#nowAge').val( myYear+"才 "+myMonth+"ヶ月 " );
    });
  });
</script>

app/views/children/_edit_class.html.erb
<% provide(:class_text, 'edit-class') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">クラス変更</h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= form_with(model: @child, url: update_class_path(@child), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @child %>
          
            <%= f.label :class_name, class: "label-#{yield(:class_text)}" %>
            <%= f.select :classroom_id, [['ひよこ', 1],['あひる', 2], ['ぺんぎん', 3]], {selected: @child.classroom_id, include_blank: false}, class: "form_control" %>
          
            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-light btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/children/_new.erb
<% provide(:class_text, 'new-child') %>
<% provide(:button_text, '登録') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">園児情報追加</h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= form_with(model: @child, url: parent_children_path(@parent), local: true) do |f| %>
            <%= render 'shared/error_messages', object: @child %>
          
            <%= f.label :child_name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :child_name, class: "form-control" %>
          
            <%= f.label :age, class: "label-#{yield(:class_text)}" %>
            <%= f.number_field :age, class: "form-control", min: 0, max: 5 %>
          
            <%= f.label :birthday, class: "label-#{yield(:class_text)}" %><br>
            <%= f.date_select :birthday,
                {start_year: 2010,
                end_year: (Time.now.year),
                default: Date.new(2020, 1, 1),
                use_month_numbers: true,
                date_separator: '/'} %><br>
                <!-- #date_fieldでカッコよくできる -->
          
            <%= f.radio_button :gender, :man %>
            <%= f.label :gender, "男", {value: :man, style: "display: inline-block;"} %>
            <%= f.radio_button :gender, :woman %>
            <%= f.label :gender, "女", {value: :woman, style: "display: inline-block;"} %><br>
          
            <%= f.label :class_name, class: "label-#{yield(:class_text)}" %>
            <%= f.collection_select :classroom_id, @classrooms, :id, :class_name, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/children/_new.html.erb
<% provide(:class_text, 'new-child') %>
<% provide(:button_text, '登録') %>

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css">
</head>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">園児情報追加</h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= form_with(model: @child, url: parent_children_path(@parent), local: true, id: "changeAge") do |f| %>
            <%= render 'shared/error_messages', object: @child %>
          
            <%= f.label :child_name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :child_name, class: "form-control" %>
          
            <%= f.label :birthday, class: "label-#{yield(:class_text)}" %><br>
            <%= f.text_field :birthday, {class: "form-control dp", id: "birthdayYMD"} %>
            
            <!-- %= raw sprintf(f.date_field( :birthday,
                start_year: 2010,
                end_year: (Time.now.year),
                default: Date.new(2020, 1, 1),
                use_month_numbers: true,
                date_separator: '%s'),'年','月') %><br>
                <!-- #date_fieldでカッコよくできる -->

            <%= f.label :age, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :age, {class: "form-control", id: "nowAge"} %>
          
            <%= f.radio_button :gender, :man %>
            <%= f.label :gender, "男", {value: :man, style: "display: inline-block;"} %>
            <%= f.radio_button :gender, :woman %>
            <%= f.label :gender, "女", {value: :woman, style: "display: inline-block;"} %><br>
          
            <%= f.label :class_name, class: "label-#{yield(:class_text)}" %>
            <%= f.collection_select :classroom_id, @classrooms, :id, :class_name, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-light btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $(".dp").datepicker( {
      changeYear: true,  // 年選択をプルダウン化
      changeMonth: true,  // 月選択をプルダウン化
      yearRange: "-5:" // 現在日付の5年前～5年後まで選択可能
    } );
  });
</script>

<script>
  $(function(){
    $('#birthdayYMD').change(function() {
      birthday_ymd = $('#birthdayYMD').val();
      retBirth = birthday_ymd.split("/");
      y = parseInt(retBirth[0], 10);
      m = parseInt(retBirth[1], 10);
      d = parseInt(retBirth[2], 10);

      myNow = new Date();    // 現在
      myBirth = new Date( 1970, 0, d );    // 基準日
      myBirth.setTime( myNow.getTime() - myBirth.getTime() );    // getTimeは1970年からの経過ミリ秒数を取得するメソッド

      // 求めた年月日から基準日を引く
      myYear  = myBirth.getUTCFullYear() - y;
      myMonth = myBirth.getUTCMonth() - ( m - 1 );

      // 月がマイナスなので年から繰り下げ
      if( myMonth < 0 ){
          myYear --;
          myMonth += 12;
      }

      // myDate = myBirth.getUTCDate();

      $('#nowAge').val( myYear+"才 "+myMonth+"ヶ月 " );
    });
  });
</script>

app/views/children/all.html.erb
<% provide(:title, 'All Children') %>
<% if params[:search].present?%>
  <h1>検索結果</h1>
<% elsif params[:search].blank? %>
  <h1>園児一覧</h1>
<% end %>


<div class="col-md-4 offset-md-8">
  <%= form_tag(all_path, :method => 'get') do %>
    <%= text_field_tag :search %>
    <%= submit_tag '園児名・クラス検索' %>
  <% end %>
</div>

<div class="col-md-10 offset-md-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th>名前</th>
        <th>月齢</th>
        <th>誕生日</th>
        <th>性別</th>
        <th>クラス</th>
        <th>クラス変更</th>
        <th>削除</th>
      </tr>
    </thead>

    <% @children.each do |child| %>
      <tr>
        <td><%= child.child_name %></td>
        <td><%= child.age %></td>
        <% if child.birthday != nil %>
          <td><%= l(child.birthday, format: :default) %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= child.gender_i18n %></td>
        <td><%= Classroom.find(child.classroom_id).class_name %></td>
        <td>
          <%= link_to "編集", edit_class_path(child), remote: true, class: "btn btn-success" %>
        </td>
        <td>
          <%= link_to "削除", destroy_from_admin_path(child), method: :delete,
          data: { confirm: "削除してよろしいですか？" },
          class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

<div id="edit-class" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/children/edit_class.js.erb
$("#edit-class").html("<%= escape_javascript(render 'edit_class') %>");
$("#edit-class").modal("show");

app/views/children/show.html.erb
<% provide(:title, @child.child_name) %>
<h1><%= @child.child_name %>の連絡帳</h1>

<!--園児詳細テーブル-->
<div>
  <%= form_with(model: @attendance, url: parent_child_attendance_path(@parent, @child, @attendance), local: true, method: :patch, id: "show-children") do |f| %>
    <%= f.hidden_field :worked_on, :value => @day %>
    <table class="table table-bordered table-striped table-condensed">
      <tr>
        <th colspan="6">
          <%= link_to " 本日 ", parent_child_path(@parent, @child, date: Date.today), class: "btn btn-primary" %>
          <%= link_to "< 前日　", parent_child_path(@parent, @child, date: @day.yesterday) %>
          <b><%= l(@day, format: :long)%></b>
          <%= link_to "　翌日 >", parent_child_path(@parent, @child, date: @day.tomorrow) %>
        </th>
      </tr>
      <tr>
        <th colspan="6", class="first">登園予定情報</th>
      </tr>
      <tr>
        <td colspan="6"><%= f.select :status_attendance, [['登園予定', 1], ['欠席', 2]], {include_blank: false}, id: "changeSelect" %></td>
      </tr>
      
      <!-- 欠席で更新済みの場合のshow画面 -->
      <tbody id="absence-children">
        <tr>
          <th colspan="6", class="first">欠席理由</th>
        </tr>
        <tr>
          <td colspan="6"><%= f.text_area :reason_of_absence, class: "form_control" %></td>
        </tr>
      </tbody>

      <!-- 欠席以外の場合のshow画面 -->
        <tbody id="attend-children" style="display: block;">
          <tr>
            <th>登園予定時間</th>
              <td><%= f.time_select :attendance_time, :default => {:hour => '8', :minute => '30'}, :minute_step => 15, class: "form_control" %></td>
            <th>お迎え予定時間</th>
              <td><%= f.time_select :pick_up_time, :default => {:hour => '17', :minute => '00'}, :minute_step => 15, class: "form_control" %></td>
            <th>お迎えの方</th>
              <td><%= f.select :pick_up_person, ['母', '父', '祖母', '祖父', 'おば', 'おじ'], {include_blank: false}, class: "form-control" %></td>
          </tr>
          <tr>
            <th>ご機嫌</th>
              <td><%= f.select :feeling, ['普', '良', '悪'], {include_blank: false}, class: "form-control" %></td>
            <th>体温</th>
              <td colspan="3"><%= f.number_field :temp, :value =>"36.5", step: '0.1', class: "form-control" %></td>
          </tr>
          <tr>
            <th colspan="6", class="first">食事</th>
          </tr>
          <tr>
            <th>夕食時間</th>
              <td colspan="3"><%= f.time_select :dinner_time, :default => {:hour => '18', :minute => '00'}, :minute_step => 15, class: "form_control" %></td>
            <th>夕食量</th>
              <td colspan="3"><%= f.select :amount_dinner, ['普', '少', '多'], {include_blank: false}, class: "form-control" %></td>
          </tr>
          <tr>
            <th>朝食時間</th>
              <td colspan="3"><%= f.time_select :morning_time, :default => {:hour => '7', :minute => '30'}, :minute_step => 15, class: "form_control" %></td>
            <th>朝食量</th>
              <td colspan="3"><%= f.select :amount_morning, ['普', '少', '多'], {include_blank: false}, class: "form-control" %></td>
          </tr>
          <tr>
            <th>おやつ①</th>
              <% if @attendance.first_snack != nil %>
                <td colspan="3"><%= l(@attendance.first_snack, format: :time) %></td>
              <% else %>
                <td colspan="3"></td>
              <% end %>
            <th>食べた量</th>
              <td colspan="3"><%= @attendance.amount_1_snack %></td>
          </tr>
          <tr>
            <th>昼食時間</th>
              <% if @attendance.lunch_time != nil %>
                <td colspan="3"><%= l(@attendance.lunch_time, format: :time) %></td>
              <% else %>
                <td colspan="3"></td>
              <% end %>
            <th>昼食量</th>
              <td colspan="3"><%= @attendance.amount_lunch %></td>
          </tr>
          <tr>
            <th>おやつ②</th>
              <% if @attendance.second_snack != nil %>
                <td colspan="3"><%= l(@attendance.second_snack, format: :time) %></td>
              <% else %>
                <td colspan="3"></td>
              <% end %>
            <th>食べた量</th>
              <td colspan="3"><%= @attendance.amount_2_snack %></td>
          </tr>
          <tr>
            <th>排便</th>
              <td colspan="3">
                <%= f.time_select :toilet_time, :default => {:hour => '0', :minute => '00'},minute_step: 15, class: "form_control" %>
                <p style="color:red; font-size:80%">※無の場合は00表示
              </td>
            <th>便の状況</th>
              <td colspan="3"><%= f.select :toilet_status, ['普通', '硬め', '柔らかめ'], {include_blank: false}, class: "form-control" %></td>
          </tr>
          <tr>
            <th colspan="6", class="first">睡眠</th>
          </tr>
          <tr>
            <th>就寝時間</th>
              <td colspan="3">
                <%= f.time_select :start_night_sleep, :default => {:hour => '20', :minute => '30'}, :minute_step => 15, class: "form_control" %> 〜
                <%= f.time_select :end_night_sleep, :default => {:hour => '7', :minute => '00'}, :minute_step => 15, class: "form_control" %>
              </td>
            <th>お昼寝時間</th>
              <% if @attendance.start_afternoon_sleep != nil && @attendance.end_afternoon_sleep != nil %>
                <td colspan="3">
                  <%= l(@attendance.start_afternoon_sleep, format: :time) %> 〜
                  <%= l(@attendance.end_afternoon_sleep, format: :time) %>
                </td>
              <% else %>
                <td colspan="3"></td>
              <% end %>
          </tr>
          <tr>
            <th colspan="6", class="first">園児の様子</th>
          </tr>
          <tr>
            <th>家庭での様子</th>
              <td colspan="5"><%= f.text_area :status_at_home, class: "form_control" %></td>
          </tr>
          <tr>
            <th>園での様子</th>
              <td colspan="5" class="entered_form"><%= @attendance.status_at_school %></td>
          </tr>
          <tr>
            <th colspan="6", class="first">連絡事項</th>
          </tr>
          <tr>
            <th>家庭からの連絡事項</th>
              <td colspan="5"><%= f.text_area :info_from_home, class: "form_control" %></td>
          </tr>
          <tr>
            <th>園からの連絡事項</th>
              <td colspan="5" class="entered_form"><%= @attendance.info_from_school %></td>
          </tr>
        </tbody>
    </table>

    <div class="center">
      <%= f.check_box :send_check %>
      <%= f.label :提出内容を確認しました %><br>
      <%= f.submit "提出する", class: "btn btn-lg btn-primary" %>
      <%= link_to "キャンセル", parent_path(@parent), class: "btn btn-lg btn-light" %>
    </div>
  <% end %>
</div>

<script>
  $(function() {
    '<% if @attendance.status_attendance == '2' %>'
      $('#attend-children').hide();
      $('#absence-children').show();
    '<% else %>'
      $('#attend-children').show();
      $('#absence-children').hide();
    '<% end %>'
    $('#changeSelect').change(function() {
      let val = $(this).val();
      if(val == 1){
        $('#attend-children').show();
        $('#absence-children').hide();
      }
      else{
        $('#attend-children').hide();
        $('#absence-children').show();
      }
    });
  });
</script>