config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  root 'home#top'

  # ログイン機能
  get    'parent/login', to: 'sessions#parent_login'
  get    'teacher/login', to: 'sessions#teacher_login'
  post   'parent/login', to: 'sessions#parent_create'
  post   'teacher/login', to: 'sessions#teacher_create'
  delete 'parent/logout', to: 'sessions#parent_destroy'
  delete 'teacher/logout', to: 'sessions#teacher_destroy'

  # # LINEログインAPI用
  # get '/parents/auth/line', to: 'parents#line', as: :parents_auth
  # get '/parents/auth/line/callback', to: 'parents#line_login', as: :parents_auth_callback
  # get '/parents/auth/failure', to: 'parents#auth_failure', as: :parents_auth_failure
  
  # get '/teachers/auth/line', to: 'teachers#line', as: :teachers_auth
  # get '/teachers/auth/line/callback', to: 'teachers#line_login', as: :teachers_auth_callback
  # get '/teacheres/auth/failure', to: 'teachers#auth_failure', as: :teachers_auth_failure

  # LINEボットAPI用
  post '/callback' => 'line_bot#callback'

  # 保護者&保護者に紐付く園児
  resources :parents do
    member do
      get 'edit_manag_info' # 管理者が編集可能な情報
      patch 'update_manag_info' # 管理者が編集可能な情報の更新
    end
    resources :children do
      resources :attendances, only: [:update, :index] do
        member do
          get 'confirm_attendance' # 連絡帳確認ボタン
        end
      end
    end
  end

  # 管理者のみが表示可能な園児一覧
  get    'children', to: 'children#all', as: 'all'
  delete 'children/:id', to: 'children#destroy_from_admin', as: 'destroy_from_admin'
  get    'children/edit_class/:id', to: 'children#edit_class', as: 'edit_class'
  patch  'children/update_class/:id', to: 'children#update_class', as: 'update_class'

  # 管理者&保育者
  resources :teachers do
    member do
      get 'edit_manag_info' # 管理者が編集可能な情報
      patch 'update_manag_info' # 管理者が編集可能な情報の更新
      get 'edit_attendance' # 園児の連絡帳画面取得
      patch 'update_attendance/:child_id', to: 'teachers#update_attendance', as: 'update_attendance' # 園児の連絡帳更新
      get 'all_children' # 担当園児一覧表示
      get 'index_attendance/:child_id', to: 'teachers#index_attendance', as: 'index_attendance' # 連絡帳一覧表示
      get 'confirm_attendance/:child_id/:attendance_id', to: 'teachers#confirm_attendance', as: 'confirm_attendance' # 連絡帳確認ボタン
    end
  end

  resources :notices
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Classroomとの親子関係
  belongs_to :classroom

  # 「remember_token」という仮想の属性を作成
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def Teacher.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def Teacher.new_token
    SecureRandom.urlsafe_base64
  end

   # 永続セッションのためハッシュ化したトークンをデータベースに記憶する
  def remember
    self.remember_token = Teacher.new_token
    update_attribute(:remember_digest, Teacher.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

  # 保育者一覧のsearch
  def self.search(search)
    return Teacher.all unless search
    # 下記コードの問題点は、クラス名が登録されていないTeacherのレコードは拾ってこない事
    Teacher.joins(:classroom).where(['name LIKE? OR staff_id LIKE? OR class_name LIKE?', "%#{search}%", "%#{search}%", "%#{search}%"])
    # Teacher.joins(:classroom).where(classroom: {['class_name LIKE?', "%#{search}%"]})
    #                          .where(['name LIKE? OR staff_id LIKE?', "%#{search}%", "%#{search}%"])
    # Teacher.where(['name LIKE? OR staff_id LIKE?', "%#{search}%", "%#{search}%"])
  end

  # # LINEログイン
  # def self.from_omniauth(auth)
  #   teacher = Teacher.where('email = ?', auth.info.email).first
  #   if teacher.blank?
  #     teacher = Teacher.new
  #   end
  #   teacher.uid   = auth.uid
  #   teacher.name  = auth.info.name
  #   teacher.email = auth.info.email
  #   teacher.oauth_token = auth.credentials.token
  #   teacher.oauth_expires_at = Time.at(auth.credentials.expires_at)
  #   teacher
  # end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy, :edit_manag_info, :update_manag_info, 
                                    :edit_attendance, :update_attendance, :all_children, :index_attendance, :confirm_attendance]
  before_action :logged_in_teacher, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_teacher, only: [:edit, :update]
  before_action :admin_teacher, only: [:show, :all_children]
  before_action :not_admin_teacher, only: [:edit_manag_info, :update_manag_info, :destroy]

  # 先生一覧
  def index
    @teachers = Teacher.paginate(page: params[:page], per_page: 10)
    if params[:search].present?
      @teachers = Teacher.paginate(page: params[:page]).search(params[:search]) 
    end
  end

  # 出欠園児一覧
  def show
    @classroom = Classroom.find(@teacher.classroom_id)
    # @children = Child.joins(:classroom, :attendances).where(attendances: {status_attendance: "1"})
    @attend_children = @classroom.children.joins(:attendances).where(attendances: {status_attendance: "1", worked_on: Date.today}).order(:birthday)
    @absence_children = @classroom.children.joins(:attendances).where(attendances: {status_attendance: "2", worked_on: Date.today}).order(:birthday)
  end

  # 連絡帳の返信
  def edit_attendance
    @child = Child.find(params[:child_id])
    @attendance = @child.attendances.find_by(worked_on: Date.current)
  end

  # 連絡帳の返信の更新
  def update_attendance
    @child = Child.find(params[:child_id])
    @attendance = @child.attendances.find_by(worked_on: Date.current)
    if params[:attendance][:reply_check] == "1"
      @attendance.update_attributes(edit_attendance_params)
      flash[:success] = "#{@child.child_name}の連絡帳を返信しました。"
    else
      flash[:danger] = "#{@child.child_name}の返信内容確認のチェックが入っていません。"
      redirect_to edit_attendance_teacher_url(@teacher, child_id: @child) and return
    end
    redirect_to @teacher and return
  end

  # 担当園児一覧
  def all_children
    @classroom = Classroom.find(@teacher.classroom_id)
    @all_children = @classroom.children.order(:birthday)
  end

  # 園児の連絡帳一覧
  def index_attendance
    # @classroom = Classroom.find(@teacher.classroom_id)
    @child = Child.find(params[:child_id])
    @parent = Parent.find(@child.parent_id)
    # indexを最初に開いた時にはまだparams[:month]は飛んできていない為下記の条件分岐が必要となる。
    if params[:month].blank?
      @month = Date.today
    else
      @month = params[:month].to_date
    end
    @attendances = @child.attendances.where(worked_on: @month.all_month).where.not(worked_on: nil)
  end

  # 園児の連絡帳の確認ボタン
  def confirm_attendance
    @child = Child.find(params[:child_id])
    @attendance = @child.attendances.find(params[:attendance_id])
  end

  # 先生ユーザー作成
  def new
    @teacher = Teacher.new
  end

  # 先生ユーザー追加
  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      log_in_teacher @teacher
      flash[:success] = '新規作成に成功しました。'
      redirect_to @teacher
    else
      render :new
    end
  end

  # 基本情報編集
  def edit
  end

  # 基本情報更新
  def update
    if @teacher.update_attributes(teacher_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @teacher
    else
      render :edit      
    end
  end

  # 先生の削除
  def destroy
    @teacher.destroy
    flash[:success] = "#{@teacher.name}のデータを削除しました。"
    redirect_to teachers_url
  end

  # 管理者が変更可能な保育者情報編集
  def edit_manag_info
  end

  # 管理者が変更可能な保育者情報更新
  def update_manag_info
    if @teacher.update_attributes(manag_info_params)
      flash[:success] = "#{@teacher.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@teacher.name}の更新は失敗しました。<br>" + @parent.errors.full_messages.join("<br>")
    end
    redirect_to teachers_url
  end

  # # LINEログイン
  # def line_login
  #   @teacher = Teacher.from_omniauth(request.env["omniauth.auth"])
  #     result = @teacher.save(context: :line_login)
  #     if result
  #       log_in_teacher @teacher
  #       redirect_to @teacher
  #     else
  #       redirect_to teacher_auth_failure_path
  #     end
  # end
  
  # #認証に失敗した際の処理
  # def auth_failure 
  #   @teacher = Teacher.new
  #   render '任意のアクション'
  # end

  private

      def teacher_params
        params.require(:teacher).permit(:name, :email, :staff_id, :class_name, :password, :password_confirmation)
      end

      def manag_info_params
        params.require(:teacher).permit(:staff_id, :classroom_id)
      end

      def edit_attendance_params
        params.require(:attendance).permit(:first_snack, :amount_1_snack, :lunch_time, :amount_lunch, :second_snack, 
          :amount_2_snack,:start_afternoon_sleep, :end_afternoon_sleep, :status_at_school, :info_from_home, :info_from_school, :reply_check)
      end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_edit_manag_info.html.erb
<% provide(:class_text, 'manag-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">編集画面</h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= form_with(model: @teacher, url: update_manag_info_teacher_path(@teacher), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @teacher %>
          
            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :name, class: "form-control", disabled: true %>
          
            <%= f.label :email, class: "label-#{yield(:class_text)}" %>
            <%= f.email_field :email, class: "form-control", disabled: true %>

            <%= f.label :staff_id, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :staff_id, class: "form-control" %>
          
            <%= f.label "クラス名", class: "label-#{yield(:class_text)}" %>
            <%= f.select :classroom_id, [['ひよこ', 1],['あひる', 2], ['ぺんぎん', 3]], {selected: @teacher.classroom_id, include_blank: false}, class: "form_control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-light btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/teachers/all_children.html.erb
<% provide(:title, @teacher.name) %>
<h1><%= @teacher.name %> 先生</h1>

<h3>担当園児一覧（<%= @classroom[:class_name] %>）</h3>

<!--担当園児一覧テーブル-->
<div>
  <table class="table table-bordered table-striped table-condensed" id="index-children">
    <tr>
      <th>名前</th>
      <th>月齢</th>
      <th>誕生日</th>
      <th>性別</th>
      <th>連絡帳一覧</th>
    </tr>

    <% @all_children.each do |child| %>
      <tr>
        <td><%= child.child_name %></td>
        <td><%= child.age %></td>
        <% if child.birthday != nil %>
          <td><%= l(child.birthday, format: :default) %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= child.gender_i18n %></td>
        <td><%= link_to "一覧", index_attendance_teacher_path(@teacher, child), class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/teachers/confirm_attendance.html.erb
<h1><%= @child.child_name %>の連絡帳</h1>

<!-- 登園の場合のshow画面 -->
<% if @attendance.status_attendance == "1" %>
  <table class="table table-bordered table-striped table-condensed", id="show-children">
    <tr>
      <th colspan="6">
        <%= l(@attendance.worked_on, format: :long)%>
      </th>
    </tr>
    <tr>
      <th colspan="6", class="first">登園予定情報</th>
    </tr>
    <tr>
      <td colspan="6">登園</td>
    </tr>
    
    <tbody id="attend-children" style="display: block;">
      <tr>
        <th>登園予定時間</th>
          <td><%= l(@attendance.attendance_time, format: :time) %></td>
        <th>お迎え予定時間</th>
          <td><%= l(@attendance.pick_up_time, format: :time) %></td>
        <th>お迎えの方</th>
          <td><%= @attendance.pick_up_person %></td>
      </tr>
      <tr>
        <tr>
          <th>ご機嫌</th>
            <td><%= @attendance.feeling %></td>
          <th>体温</th>
            <td colspan="3"></td>
        </tr>
        <tr>
          <th colspan="6", class="first">食事</th>
        </tr>
        <tr>
          <th>夕食時間</th>
            <td colspan="3"><%= l(@attendance.dinner_time, format: :time) %></td>
          <th>夕食量</th>
            <td colspan="3"><%= @attendance.amount_dinner %></td>
        </tr>
        <tr>
          <th>朝食時間</th>
            <td colspan="3"><%= l(@attendance.morning_time, format: :time) %></td>
          <th>朝食量</th>
            <td colspan="3"><%= @attendance.amount_morning %></td>
        </tr>
      <tr>
        <th>おやつ①</th>
          <% if @attendance.first_snack != nil %>
            <td colspan="3"><%= l(@attendance.first_snack, format: :time) %></td>
          <% else %>
            <td colspan="3"></td>
          <% end %>
        <th>食べた量</th>
          <td colspan="3"><%= @attendance.amount_1_snack %></td>
      </tr>
      <tr>
        <th>昼食時間</th>
          <% if @attendance.lunch_time != nil %>
            <td colspan="3"><%= l(@attendance.lunch_time, format: :time) %></td>
          <% else %>
            <td colspan="3"></td>
          <% end %>
        <th>昼食量</th>
          <td colspan="3"><%= @attendance.amount_lunch %></td>
      </tr>
      <tr>
        <th>おやつ②</th>
          <% if @attendance.second_snack != nil %>
            <td colspan="3"><%= l(@attendance.second_snack, format: :time) %></td>
          <% else %>
            <td colspan="3"></td>
          <% end %>
        <th>食べた量</th>
          <td colspan="3"><%= @attendance.amount_2_snack %></td>
      </tr>
      <tr>
        <th>排便</th>
          <td colspan="3">
            <%= l(@attendance.toilet_time, format: :time) %>
            <p style="color:red; font-size:80%">※無の場合は00表示
          </td>
        <th>便の状況</th>
          <td colspan="3"><%= @attendance.toilet_status %></td>
      </tr>
      <tr>
        <th colspan="6", class="first">睡眠</th>
      </tr>
      <tr>
        <th>就寝時間</th>
          <td colspan="3">
            <%= l(@attendance.start_night_sleep, format: :time) %> 〜
            <%= l(@attendance.end_night_sleep, format: :time) %>
        <th>お昼寝時間</th>
          <% if @attendance.start_afternoon_sleep != nil && @attendance.end_afternoon_sleep != nil %>
            <td colspan="3">
              <%= l(@attendance.start_afternoon_sleep, format: :time) %> 〜
              <%= l(@attendance.end_afternoon_sleep, format: :time) %>
            </td>
          <% else %>
            <td colspan="3"></td>
          <% end %>
      </tr>
      <tr>
        <th colspan="6", class="first">園児の様子</th>
      </tr>
      <tr>
        <th>家庭での様子</th>
          <td colspan="5" class="entered_form"><%= @attendance.status_at_home %></td>
      </tr>
      <tr>
        <th>園での様子</th>
          <td colspan="5" class="entered_form"><%= @attendance.status_at_school %></td>
      </tr>
      <tr>
        <th colspan="6", class="first">連絡事項</th>
      </tr>
      <tr>
        <th>家庭からの連絡事項</th>
          <td colspan="5" class="entered_form"><%= @attendance.info_from_home %></td>
      </tr>
      <tr>
        <th>園からの連絡事項</th>
          <td colspan="5" class="entered_form"><%= @attendance.info_from_school %></td>
      </tr>
    </tbody>
  </table>
<!-- 欠席で更新済みの場合のshow画面 -->
<% else %>
  <table class="table table-bordered table-striped table-condensed", id="show-children">
    <tr>
      <th colspan="6">
        <%= l(@attendance.worked_on, format: :long)%>
      </th>
    </tr>
    <tr>
      <th colspan="6", class="first">登園予定情報</th>
    </tr>
    <tr>
      <td colspan="6">欠席</td>
    </tr>
    
    <tbody id="absence-children">
      <tr>
        <th colspan="6", class="first">欠席理由</th>
      </tr>
      <tr>
        <td colspan="6"><%= @attendance.reason_of_absence %></td>
      </tr>
    </tbody>
  </table>
<% end %>
<div class="center">
  <%= link_to "<　戻る", index_attendance_teacher_path(@teacher, @child), class: "btn btn-outline-secondary" %>
</div>

app/views/teachers/edit_attendance.html.erb
<% provide(:title, @child.child_name) %>
<h1><%= @child.child_name %>の連絡帳</h1>

<!--園児詳細テーブル-->
<div>
  <%= form_with(model: @attendance, url: update_attendance_teacher_path(@teacher, @child), method: :patch, id: "show-children") do |f| %>
    <table class="table table-bordered table-striped table-condensed">
      <tr>
        <th colspan="6">
          <%= l(Date.current, format: :long)%>
        </th>
      </tr>
      <tr>
        <th colspan="6", class="first">登園予定情報</th>
      </tr>
      <tr>
        <td colspan="6">登園予定</td>
      </tr>

      <!-- 欠席以外の場合のshow画面 -->
      <tr>
        <th>登園予定時間</th>
          <td><%= l(@attendance.attendance_time, format: :time) %></td>
        <th>お迎え予定時間</th>
          <td><%= l(@attendance.pick_up_time, format: :time) %></td>
        <th>お迎えの方</th>
          <td><%= @attendance.pick_up_person %></td>
      </tr>
      <tr>
        <th>ご機嫌</th>
          <td><%= @attendance.feeling %></td>
        <th>体温</th>
          <td colspan="3"><%= @attendance.temp %></td>
      </tr>
      <tr>
        <th colspan="6", class="first">食事</th>
      </tr>
      <tr>
        <th>夕食時間</th>
          <td colspan="3"><%= l(@attendance.dinner_time, format: :time) %></td>
        <th>夕食量</th>
          <td colspan="3"><%= @attendance.amount_dinner %></td>
      </tr>
      <tr>
        <th>朝食時間</th>
          <td colspan="3"><%= l(@attendance.morning_time, format: :time) %></td>
        <th>朝食量</th>
          <td colspan="3"><%= @attendance.amount_morning %></td>
      </tr>
      <tr>
        <th>おやつ①</th>
          <td colspan="3"><%= f.time_select :first_snack, :default => {:hour => '9', :minute => '30'}, :minute_step => 15, class: "form_control" %></td>
        <th>食べた量</th>
          <td colspan="3"><%= f.select :amount_1_snack, ['普', '少', '多'], {include_blank: false}, class: "form-control" %></td>
      </tr>
      <tr>
        <th>昼食時間</th>
          <td colspan="3"><%= f.time_select :lunch_time, :default => {:hour => '11', :minute => '30'}, :minute_step => 15, class: "form_control" %></td>
        <th>昼食量</th>
          <td colspan="3"><%= f.select :amount_lunch, ['普', '少', '多'], {include_blank: false}, class: "form-control" %></td>
      </tr>
      <tr>
        <th>おやつ②</th>
          <td colspan="3"><%= f.time_select :second_snack, :default => {:hour => '15', :minute => '30'}, :minute_step => 15, class: "form_control" %></td>
        <th>食べた量</th>
          <td colspan="3"><%= f.select :amount_2_snack, ['普', '少', '多'], {include_blank: false}, class: "form-control" %></td>
      </tr>
      <tr>
        <th>排便</th>
          <td colspan="3">
            <%= l(@attendance.toilet_time, format: :time) %>
            <p style="color:red; font-size:80%">※無の場合は00表示
          </td>
        <th>便の状況</th>
          <td colspan="3"><%= @attendance.toilet_status %></td>
      </tr>
      <tr>
        <th colspan="6", class="first">睡眠</th>
      </tr>
      <tr>
        <th>就寝時間</th>
          <td colspan="3">
            <%= l(@attendance.start_night_sleep, format: :time) %> 〜
            <%= l(@attendance.end_night_sleep, format: :time) %>
          </td>
        <th>お昼寝時間</th>
          <td colspan="3">
            <%= f.time_select :start_afternoon_sleep, :default => {:hour => '12', :minute => '30'}, :minute_step => 15, class: "form_control" %> 〜
            <%= f.time_select :end_afternoon_sleep, :default => {:hour => '13', :minute => '30'}, :minute_step => 15, class: "form_control" %>
          </td>
      </tr>
      <tr>
        <th colspan="6", class="first">園児の様子</th>
      </tr>
      <tr>
        <th>家庭での様子</th>
          <td colspan="5" class="entered_form"><%= @attendance.status_at_home %></td>
      </tr>
      <tr>
        <th>園での様子</th>
          <td colspan="5"><%= f.text_area :status_at_school, class: "form_control" %></td>
      </tr>
      <tr>
        <th colspan="6", class="first">連絡事項</th>
      </tr>
      <tr>
        <th>家庭からの連絡事項</th>
          <td colspan="5" class="entered_form"><%= @attendance.info_from_home %></td>
      </tr>
      <tr>
        <th>園からの連絡事項</th>
          <td colspan="5"><%= f.text_area :info_from_school, class: "form_control" %></td>
      </tr>
    </table>

    <div class="center">
      <%= f.check_box :reply_check %>
      <%= f.label :返信内容を確認しました %><br>
      <%= f.submit "返信する", class: "btn btn-lg btn-primary" %>
      <%= link_to "キャンセル", teacher_path(@teacher), class: "btn btn-lg btn-light" %>
    </div>
  <% end %>
</div>

app/views/teachers/edit_manag_info.js.erb
$("#edit-manag-info").html("<%= escape_javascript(render 'edit_manag_info') %>");
$("#edit-manag-info").modal("show");

app/views/teachers/index.html.erb
<% provide(:title, 'All Teachers') %>
<% if params[:search].present?%>
  <h1>検索結果</h1>
<% elsif params[:search].blank? %>
  <h1>保育者一覧</h1>
<% end %>

<div class="col-md-4 offset-md-8">
  <%= form_tag(teachers_path, :method => 'get') do %>
    <%= text_field_tag :search %>
    <%= submit_tag '項目検索' %>
  <% end %>
</div>

<div class="col-md-10 offset-md-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= Teacher.human_attribute_name :name %></th>
        <th><%= Teacher.human_attribute_name :staff_id %></th>
        <th><%= Classroom.human_attribute_name :class_name %></th>
      </tr>
    </thead>

    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.staff_id %></td>
          <% classroom = Classroom.find(teacher.classroom_id) %>
        <td><%= classroom.class_name %></td>
        <td>
          <%= link_to "編集", edit_manag_info_teacher_path(teacher), remote: true, class: "btn btn-success" %>
          <%= link_to "削除", teacher, method: :delete,
          data: { confirm: "削除してよろしいですか？" },
          class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>


<!--モーダルウインドウ表示-->
<div id="edit-manag-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/teachers/index_attendance.html.erb
<h1><%= @child.child_name %>の連絡帳一覧</h1>

<%= link_to "<　前月", index_attendance_teacher_path(@teacher, @child, month: @month.last_month), class: "btn btn-outline-info" %>
<%= link_to " 当月 ", index_attendance_teacher_path(@teacher, @child, month: Date.today), class: "btn btn-outline-info" %>
<%= link_to "翌月　>", index_attendance_teacher_path(@teacher, @child, month: @month.next_month), class: "btn btn-outline-info" %>

<!--連絡帳一覧テーブル-->
<div>
  <table class="table table-bordered table-striped table-condensed" id="index-children">
    <tr>
      <th>日付</th>
      <th>登園情報</th>
      <th>体温</th>
      <th>登園時間</th>
      <th>降園時間</th>
      <th>お迎え</th>
      <th>家庭での様子</th>
      <th>家庭からの連絡事項</th>
      <th>園での様子</th>
      <th>園からの連絡事項</th>
      <th>詳細確認</th>
    </tr>

    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= l(attendance.worked_on, format: :short) %></td>
        <td>
          <% if attendance.status_attendance == "1" %>
            <button class="btn btn-secondary">登園</button>
          <% elsif attendance.status_attendance == "2" %>
            <button class="btn btn-outline-secondary"disabled>欠席</button>
          <% end %>
        </td>
        <td><%= attendance.temp %></td>
        <% if attendance.attendance_time != nil %>
          <td><%= l(attendance.attendance_time, format: :time) %></td>
        <% else %>
          <td></td>
        <% end %>
        <% if attendance.pick_up_time != nil %>
          <td><%= l(attendance.pick_up_time, format: :time) %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= attendance.pick_up_person %></td>
        <td><%= attendance.status_at_home %></td>
        <td><%= attendance.info_from_home %></td>
        <td><%= attendance.status_at_school %></td>
        <td><%= attendance.info_from_school %></td>
        <td><%= link_to "確認", confirm_attendance_teacher_path(@teacher, @child, attendance_id: attendance.id), class: "btn btn-info" %></td>
      </tr>
    <% end %>
  </table>
  <div class="center">
    <%= link_to "<　戻る", all_children_teacher_path(@teacher), class: "btn btn-outline-secondary" %>
  </div>
</div>