config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  root 'home#top'

  # ログイン機能
  get    'parent/login', to: 'sessions#parent_login'
  get    'teacher/login', to: 'sessions#teacher_login'
  post   'parent/login', to: 'sessions#parent_create'
  post   'teacher/login', to: 'sessions#teacher_create'
  delete 'parent/logout', to: 'sessions#parent_destroy'
  delete 'teacher/logout', to: 'sessions#teacher_destroy'

  # # LINEログインAPI用
  # get '/parents/auth/line', to: 'parents#line', as: :parents_auth
  # get '/parents/auth/line/callback', to: 'parents#line_login', as: :parents_auth_callback
  # get '/parents/auth/failure', to: 'parents#auth_failure', as: :parents_auth_failure
  
  # get '/teachers/auth/line', to: 'teachers#line', as: :teachers_auth
  # get '/teachers/auth/line/callback', to: 'teachers#line_login', as: :teachers_auth_callback
  # get '/teacheres/auth/failure', to: 'teachers#auth_failure', as: :teachers_auth_failure

  # LINEボットAPI用
  post '/callback' => 'line_bot#callback'

  # 保護者&保護者に紐付く園児
  resources :parents do
    member do
      get 'edit_manag_info' # 管理者が編集可能な情報
      patch 'update_manag_info' # 管理者が編集可能な情報の更新
    end
    resources :children do
      resources :attendances, only: [:update, :index] do
        member do
          get 'confirm_attendance' # 連絡帳確認ボタン
        end
      end
    end
  end

  # 管理者のみが表示可能な園児一覧
  get    'children', to: 'children#all', as: 'all'
  delete 'children/:id', to: 'children#destroy_from_admin', as: 'destroy_from_admin'
  get    'children/edit_class/:id', to: 'children#edit_class', as: 'edit_class'
  patch  'children/update_class/:id', to: 'children#update_class', as: 'update_class'

  # 管理者&保育者
  resources :teachers do
    member do
      get 'edit_manag_info' # 管理者が編集可能な情報
      patch 'update_manag_info' # 管理者が編集可能な情報の更新
      get 'edit_attendance' # 園児の連絡帳画面取得
      patch 'update_attendance/:child_id', to: 'teachers#update_attendance', as: 'update_attendance' # 園児の連絡帳更新
      get 'all_children' # 担当園児一覧表示
      get 'index_attendance/:child_id', to: 'teachers#index_attendance', as: 'index_attendance' # 連絡帳一覧表示
      get 'confirm_attendance/:child_id/:attendance_id', to: 'teachers#confirm_attendance', as: 'confirm_attendance' # 連絡帳確認ボタン
    end
  end

  resources :notices
end

app/models/parent.rb
class Parent < ApplicationRecord
  # childとの親子関係
  has_many :children, dependent: :destroy
  accepts_nested_attributes_for :children

  # 「remember_token」という仮想の属性を作成
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  # validates :phone_number, format: { with: VALID_PHONE_NUMBER_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def Parent.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def Parent.new_token
    SecureRandom.urlsafe_base64
  end

   # 永続セッションのためハッシュ化したトークンをデータベースに記憶する
  def remember
    self.remember_token = Parent.new_token
    update_attribute(:remember_digest, Parent.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

  # 保護者一覧のsearch
  # １行目のjoinにすると、園児名やクラス名が登録されていないParentのレコードは拾ってこない為、シンプルに親情報検索のみに
  def self.search(search)
    return Parent.all unless search
    # Parent.joins(children: :classroom).where(['name LIKE? OR relationship LIKE? OR child_name LIKE? OR class_name LIKE?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
    # Parent.joins(:children).where(['name LIKE? OR relationship LIKE? OR child_name LIKE?', "%#{search}%", "%#{search}%", "%#{search}%"])
    Parent.where(['name LIKE? OR relationship LIKE?', "%#{search}%", "%#{search}%"])
  end

  # # LINEログイン
  # def self.from_omniauth(auth)
  #   parent = Parent.where('email = ?', auth.info.email).first
  #   if parent.blank?
  #     parent = Parent.new
  #   end
  #   parent.uid   = auth.uid
  #   parent.name  = auth.info.name
  #   parent.email = auth.info.email
  #   parent.oauth_token = auth.credentials.token
  #   parent.oauth_expires_at = Time.at(auth.credentials.expires_at)
  #   parent
  # end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy, :edit_manag_info, :update_manag_info]
  before_action :logged_in_parent, only: [:show, :edit, :update]
  before_action :correct_parent, only: [:edit, :update]
  # before_action :not_admin_teacher, only: :destroy

  # 保護者一覧
  def index
    @parents = Parent.paginate(page: params[:page], per_page: 10)
    if params[:search].present?
      @parents = Parent.paginate(page: params[:page]).search(params[:search]) 
    end
  end

  # 園児情報一覧
  def show
    @children = @parent.children
  end

  # 親ユーザー作成
  def new
    @parent = Parent.new
  end

  # 親ユーザー追加
  def create
    @parent = Parent.new(parent_params)
    if @parent.save
      log_in_parent @parent
      flash[:success] = '新規作成に成功しました。'
      redirect_to @parent
    else
      render :new
    end
  end

  # 基本情報編集
  def edit
  end

  # 基本情報更新
  def update
    if @parent.update_attributes(parent_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @parent
    else
      render :edit      
    end
  end

  # 保護者削除
  def destroy
    @parent.destroy
    flash[:success] = "#{@parent.name}のデータを削除しました。"
    redirect_to parents_url
  end

  # 管理者のみ変更できる保護者編集ボタン
  # def edit_manag_info
  # end

  # def update_manag_info
  #   if @parent.update_attributes(manag_info_params)
  #     flash[:success] = "#{@parent.name}の基本情報を更新しました。"
  #   else
  #     flash[:danger] = "#{@parent.name}の更新は失敗しました。<br>" + @parent.errors.full_messages.join("<br>")
  #   end
  #   redirect_to parents_url
  # end

  # # LINEログイン
  # def line_login
  #   @parent = Parent.from_omniauth(request.env["omniauth.auth"])
  #     result = @parent.save(context: :line_login)
  #     if result
  #       log_in_parent @parent
  #       redirect_to @parent
  #     else
  #       redirect_to parent_auth_failure_path
  #     end
  # end
  
  # #認証に失敗した際の処理
  # def auth_failure 
  #   @parent = Parent.new
  #   render '任意のアクション'
  # end


  private

      def parent_params
        params.require(:parent).permit(:name, :email, :phone_number, :relationship, :password, :password_confirmation)
      end

      # def manag_info_params
      #   params.require(:parent).permit(:child_class)
      # end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_edit_manag_info.html.erb
<% provide(:class_text, 'manag-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">編集画面</h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= form_with(model: @parent, url: update_manag_info_parent_path(@parent), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @parent %>
          
            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :name, class: "form-control", disabled: true %>
          
            <%= f.label :email, class: "label-#{yield(:class_text)}" %>
            <%= f.email_field :email, class: "form-control", disabled: true %>

            <%= f.label :relationship, class: "label-#{yield(:class_text)}" %>
            <%= f.select :relationship, ['母', '父', '祖母', '祖父', 'おば', 'おじ'], {include_blank: '選択してください'}, class: "form-control", disabled: true %>
          
            <%= f.label :class_name, class: "label-#{yield(:class_text)}" %>
            <%= f.select :class_name, ['ひよこ', 'あひる', 'ぺんぎん'], {include_blank: false}, class: "form_control" %>
          
            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-light btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/parents/_form.html.erb
<%= form_with(model: @parent, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @parent %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :phone_number, class: "label-#{yield(:class_text)}" %>
  <%= f.phone_field :phone_number, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/parents/_form_p.html.erb
<%= form_with(model: @parent, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @parent %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, placeholder: "（例）○○　花子",class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, placeholder: "（例）○○○○@email.com",class: "form-control" %>

  <%= f.label :phone_number, class: "label-#{yield(:class_text)}" %>
  <%= f.telephone_field :phone_number, placeholder: "（例）0×0-0000-0000", class: "form-control" %>

  <%= f.label "園児との関係性", class: "label-#{yield(:class_text)}" %>
  <%= f.select :relationship, ['母', '父', '祖母', '祖父', 'おば', 'おじ'], {include_blank: '選択してください'}, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
  <%= link_to "キャンセル", root_path, class: "btn btn-secondary btn-block" %>
<% end %>

app/views/parents/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>保護者情報の更新</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'form_p' %>
  </div>
</div>

app/views/parents/index.html.erb
<% provide(:title, 'All Parents') %>
<% if params[:search].present?%>
  <h1>検索結果</h1>
<% elsif params[:search].blank? %>
  <h1>保護者一覧</h1>
<% end %>

<div class="col-md-4 offset-md-8">
  <%= form_tag(parents_path, :method => 'get') do %>
    <%= text_field_tag :search %>
    <%= submit_tag '保護者名検索' %>
  <% end %>
</div>

<div class="col-md-10 offset-md-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= Parent.human_attribute_name :name %></th>
        <th><%= Parent.human_attribute_name :relationship %></th>
        <th><%= Child.human_attribute_name :child_name %></th>
        <th><%= Classroom.human_attribute_name :class_name %></th>
        <th></th>
      </tr>
    </thead>

    <% @parents.each do |parent| %>
      <% children = Child.where(parent_id: parent.id) %>
      <% if children.blank? %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= parent.relationship %></td>
        <td></td>
        <td></td>
        <td>
          <!-- %= link_to "編集", edit_manag_info_parent_path(parent), remote: true, class: "btn btn-success" % -->
          <%= link_to "削除", parent, method: :delete,
          data: { confirm: "削除してよろしいですか？" },
          class: "btn btn-danger" %>
        </td>
      </tr>
      <% else %>
        <% saved_parent_name = nil %>
        <% children.each do |child| %>
          <tr>
            <% if parent.name == saved_parent_name %>
              <td></td>
              <td></td>
            <% else %>
              <td><%= parent.name %></td>
              <td><%= parent.relationship %></td>
            <% end %>

            <td><%= child.child_name %></td>
              <% classroom = Classroom.find(child.classroom_id) %>
            <td><%= classroom.class_name %></td>
            
            <% if parent.name == saved_parent_name %>
              <td></td>
            <% else %>
              <% saved_parent_name = parent.name %>
              <td>
                <!-- %= link_to "編集", edit_manag_info_parent_path(parent), remote: true, class: "btn btn-success" % -->
                <%= link_to "削除", parent, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </table>
  <%= will_paginate %>
</div>


<!--モーダルウインドウ表示-->
<div id="edit-manag-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/parents/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>保護者登録</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'form_p' %>
  </div>
</div>

app/views/parents/show.html.erb
<% provide(:title, @parent.name) %>
<h1>園児情報一覧</h1>

<!--園児登録ボタン-->
<div class="btn-parents-show">
  <%= link_to "園児新規追加", new_parent_child_path(@parent), remote: true, class: "btn btn-info" %>
</div>

<!--園児一覧テーブル-->
<div>
  <table class="table table-bordered table-striped table-condensed" id="index-children">
    <tr>
      <th>名前</th>
      <th>月齢</th>
      <th>誕生日</th>
      <th>性別</th>
      <th>クラス</th>
      <th>連絡帳</th>
      <th>連絡帳一覧</th>
    </tr>

    <% @children.each do |child| %>
      <tr>
        <td><%= link_to child.child_name, edit_parent_child_path(@parent, child), remote: true %></td>
        <td><%= child.age %></td>
        <% if child.birthday != nil %>
          <td><%= l(child.birthday, format: :default) %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= child.gender_i18n %></td>
        <td><%= Classroom.find(child.classroom_id).class_name %></td>
        <td>
        <!-- 連絡帳未提出の際、child.attendancesのレコードはまだnilなので、それがnilでない、かつそのレコードのsend_checkが入っている場合に提出済みにする。 
             仮に１行目の条件を外すと、そもそものレコードが無いために、２・３行目の条件がエラーになってしまうので必要 -->
          <% if (child.attendances.find_by(worked_on: Date.today) != nil) &&
                (child.attendances.find_by(worked_on: Date.today).send_check == true) %>
            <% if child.attendances.find_by(worked_on: Date.today).reply_check == true %>
              <%= link_to "返信有", parent_child_path(@parent, child), class: "btn btn-warning" %>
            <% else %>
              <% if child.attendances.find_by(worked_on: Date.today).status_attendance == "1" %>
                <%= link_to "登園", parent_child_path(@parent, child), class: "btn btn-secondary" %>
              <% elsif child.attendances.find_by(worked_on: Date.today).status_attendance == "2" %>
                <%= link_to "欠席", parent_child_path(@parent, child), class: "btn btn-outline-secondary" %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to "提出", parent_child_path(@parent, child), class: "btn btn-info" %>
          <% end %>
        </td>
        <td><%= link_to "一覧", parent_child_attendances_path(@parent, child), class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </table>
</div>

<div id="new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>