config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  root 'home#top'

  # ログイン機能
  get    'parent/login', to: 'sessions#parent_login'
  get    'teacher/login', to: 'sessions#teacher_login'
  post   'parent/login', to: 'sessions#parent_create'
  post   'teacher/login', to: 'sessions#teacher_create'
  delete 'parent/logout', to: 'sessions#parent_destroy'
  delete 'teacher/logout', to: 'sessions#teacher_destroy'

  # # LINEログインAPI用
  # get '/parents/auth/line', to: 'parents#line', as: :parents_auth
  # get '/parents/auth/line/callback', to: 'parents#line_login', as: :parents_auth_callback
  # get '/parents/auth/failure', to: 'parents#auth_failure', as: :parents_auth_failure
  
  # get '/teachers/auth/line', to: 'teachers#line', as: :teachers_auth
  # get '/teachers/auth/line/callback', to: 'teachers#line_login', as: :teachers_auth_callback
  # get '/teacheres/auth/failure', to: 'teachers#auth_failure', as: :teachers_auth_failure

  # LINEボットAPI用
  post '/callback' => 'line_bot#callback'

  # 保護者&保護者に紐付く園児
  resources :parents do
    member do
      get 'edit_manag_info' # 管理者が編集可能な情報
      patch 'update_manag_info' # 管理者が編集可能な情報の更新
    end
    resources :children do
      resources :attendances, only: [:update, :index] do
        member do
          get 'confirm_attendance' # 連絡帳確認ボタン
        end
      end
    end
  end

  # 管理者のみが表示可能な園児一覧
  get    'children', to: 'children#all', as: 'all'
  delete 'children/:id', to: 'children#destroy_from_admin', as: 'destroy_from_admin'
  get    'children/edit_class/:id', to: 'children#edit_class', as: 'edit_class'
  patch  'children/update_class/:id', to: 'children#update_class', as: 'update_class'

  # 管理者&保育者
  resources :teachers do
    member do
      get 'edit_manag_info' # 管理者が編集可能な情報
      patch 'update_manag_info' # 管理者が編集可能な情報の更新
      get 'edit_attendance' # 園児の連絡帳画面取得
      patch 'update_attendance/:child_id', to: 'teachers#update_attendance', as: 'update_attendance' # 園児の連絡帳更新
      get 'all_children' # 担当園児一覧表示
      get 'index_attendance/:child_id', to: 'teachers#index_attendance', as: 'index_attendance' # 連絡帳一覧表示
      get 'confirm_attendance/:child_id/:attendance_id', to: 'teachers#confirm_attendance', as: 'confirm_attendance' # 連絡帳確認ボタン
    end
  end

  resources :notices
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark fixed-top">
  <div class="container">
    <%= link_to "えんアプリ", root_path, id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon collapse-close"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if parent_logged_in? %>
          <li class="nav-item"><%= link_to "トップ　", root_path, class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "園児情報", current_parent, class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "基本情報編集", edit_parent_path(current_parent),class: "nav-link text-white" %></li>
          <li class="nav-item">
            <%= link_to "ログアウト", parent_logout_path, method: :delete, class: "nav-link text-white" %>
          </li>
        <% elsif teacher_logged_in? && !current_teacher.admin? %>
          <li class="nav-item"><%= link_to "出欠園児一覧", teacher_path(current_teacher), class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "担当園児一覧", all_children_teacher_path(current_teacher), class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "基本情報編集", edit_teacher_path(current_teacher), class: "nav-link text-white" %></li>
          <li class="nav-item">
            <%= link_to "ログアウト", teacher_logout_path, method: :delete, class: "nav-link text-white" %>
          </li>
        <% elsif teacher_logged_in? && current_teacher.admin? %>
          <li class="nav-item"><%= link_to "保育者一覧", teachers_path, class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "保護者一覧", parents_path, class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "園児一覧", all_path, class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "お知らせ一覧", notices_path, class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "基本情報編集", edit_teacher_path(current_teacher), class: "nav-link text-white" %></li>
          <li class="nav-item">
            <%= link_to "ログアウト", teacher_logout_path, method: :delete, class: "nav-link text-white" %>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "ログイン", root_path, class: "nav-link text-white" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | えんアプリ</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!-- HTML shimがこの1行で収まる -->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <!-- headerの内容がこの1行で収まる -->
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>